# Generated by Django 4.2.17 on 2024-12-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_course_created_at'),
    ]

    operations = [
    ]
