# Generated by Django 4.2.17 on 2025-01-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorshipsession',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='mentorship.resource'),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='next_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
