# Generated by Django 4.2.8 on 2025-07-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useractivity',
            table='dashboard_useractivity',
        ),
    ]
